server:
  port: 8082
  
spring:
  security:
    oauth2:
      resource server:
        jwt:
          issuer-uri: http://localhost:8181/realms/Spring-boot-banking
  cloud:
    gateway:
      routes:
        ## USER SERVICE
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/bank-user/**
        ## FUND TRANSFER SERVICE
        - id: fund-service
          uri: lb://fund-service
          predicates:
            - Path=/transfer/** # transfer
        ## CORE BANKING SERVICE
        - id: core-service
          uri: lb://core-service
          predicates:
            - Path=/user/** , /transaction/** , /accounts/**  #/api/v1/user")/api/v1/transaction")/api/v1/accounts
        ## UTILITY PAYMENTS SERVICE
        - id: utility-payment-service
          uri: lb://utility-payment-service
          predicates:
            - Path=/utility-payment/**
        ## SERVICE DISCOVERY
        - id: service-discovery
          uri: http://localhost:8081
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        - id: service-discovery-static
          uri: http://localhost:8081
          predicates:
            - Path=/eureka/**

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8081/eureka
  instance:
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: info


app:
  config:
    keycloak:
      server-url: http://localhost:8181/auth
      realm: Spring-cloud-client
      clientId: Spring-cloud-client
      client-secret: ON8PBvQPHlafnQSkF1OcPHGLhRD5vPrK
    
